# Source: platform/charts/cloudnative-pg/templates/rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: platform-cloudnative-pg-view
  labels:
    helm.sh/chart: cloudnative-pg-0.29.0
    app.kubernetes.io/name: cloudnative-pg
    app.kubernetes.io/instance: platform
    app.kubernetes.io/version: "1.30.0"
    app.kubernetes.io/managed-by: Helm
rules:
- apiGroups:
  - postgresql.cnpg.io
  resources:
  - backups
  - clusters
  - clusters/status
  - databaseroles
  - databases
  - failoverquorums
  - poolers
  - publications
  - scheduledbackups
  - imagecatalogs
  - clusterimagecatalogs
  - subscriptions
  verbs:
  - get
  - list
  - watch