# Source: platform/charts/valkey-operator/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: platform-valkey-operator
  namespace: gitops-zero-to-hero
  labels:
    helm.sh/chart: valkey-operator-0.6.0
    app.kubernetes.io/name: valkey-operator
    app.kubernetes.io/instance: platform
    app.kubernetes.io/version: "v0.6.0"
    app.kubernetes.io/managed-by: Helm
automountServiceAccountToken: true